!Recover stresses in either 2D or 3D meshes based on the deformation generated by the FEM
!subroutienes in this library

! 3D stresses: 				sig_x       sig_y       sig_z       tau_xy      tau_yz      tau_zx
! 2D axisymmetric stress: 	sig_r       sig_z       tau_rz      sig_t
! 2D plane stress: 			sig_x       sig_y       tau_xy"

module fem_stress

contains

    subroutine get_stress(evals,vvals,disp,g_coord,g_g,g_num,neq,nels,nod,ndof,ndim,nst,nn,type_2d,element,sigma, strain)
    
     USE fem_main 
	USE fem_geom 
	!use fem_stuff
    
    implicit none
    
    integer, intent(in) :: nod,ndof,ndim,nst,nels,neq,nn
    real, intent(in) :: evals(nels),vvals(nels),g_coord(ndim,nn)
    !real, intent(out) :: sigma !matrix x,y stress, shear stress [radial stress]
    
    
    integer, intent(in) :: g_num(nod,nels),g_g(ndof,nels)
    integer g(ndof),num(nod)
    real(8) :: points(1,ndim),weights(1)
    real(8) :: bee(nst,ndof),dee(nst,nst),coord(nod,ndim),fun(nod),jac(ndim,ndim),der(ndim,nod),eld(ndof),gc(ndim),deriv(ndim,nod)
    real(8), intent(out) :: sigma(nst,nels), strain(nst,nels)
    real(4), intent(in) :: disp(0:neq)
    CHARACTER(LEN=15), intent(in) ::type_2d
	CHARACTER(LEN=20) element
    integer i,iel
    
    !type_2d='axisymmetric'
    
    !#requires: global coordinates, numbering, loads
     i=1 !1 integration point for stress recovery
     
    
	 CALL sample(element,points,weights)
	 elements_3: DO iel=1,nels
	     CALL deemat(dee,evals(iel),vvals(iel))
	     num=g_num(:,iel)
	     coord=TRANSPOSE(g_coord(:,num)) 
	     g=g_g(:,iel) 
	     eld=disp(g)
		 CALL shape_fun(fun,points,i) 
		 CALL shape_der(der,points,i)
		 gc=MATMUL(fun,coord) 
		 jac=MATMUL(der,coord) 
		 CALL invert(jac)
		 deriv=MATMUL(jac,der) 
		 CALL beemat(bee,deriv)
		 IF(type_2d=='axisymmetric')THEN
		   gc=MATMUL(fun,coord) 
		   bee(4,1:ndof-1:2)=fun(:)/gc(1)
		 END IF
		 strain(:,iel) = MATMUL(bee,eld)
		 sigma(:,iel)  = MATMUL(dee,strain(:,iel)) 
	 END DO elements_3
    
    
    end subroutine
    
end module
    
